# Generated by Django 6.1 on 2026-08-19 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_page', models.CharField(blank=True, max_length=100, null=True)),
                ('other_accounts', models.JSONField(blank=True, default=dict)),
                ('package_name', models.CharField(default='Enterprise Digital Suite', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('payment_status', models.CharField(default='Paid', max_length=20)),
                ('videos_planned', models.IntegerField(default=20)),
                ('videos_completed', models.IntegerField(default=12)),
                ('posters_planned', models.IntegerField(default=30)),
                ('posters_completed', models.IntegerField(default=24)),
                ('reels_count', models.IntegerField(default=15)),
                ('posts_count', models.IntegerField(default=28)),
                ('stories_count', models.IntegerField(default=45)),
                ('campaigns_count', models.IntegerField(default=3)),
                ('content_status', models.CharField(default='On Track', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team', models.ManyToManyField(blank=True, related_name='social_clients', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='clients.client')),
            ],
        ),
    ]
