# Generated by Django 6.1 on 2026-09-11 12:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaclient',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_social_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='company_base',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='current_followers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='has_run_ads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='meta_ads_manager_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='monthly_deliverables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='page_status',
            field=models.CharField(default='Existing Page', max_length=50),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='price_per_post',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='price_per_video',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='socialmediaclient',
            name='pricing_model',
            field=models.CharField(default='Monthly Retainer', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='campaigns_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='content_status',
            field=models.CharField(default='Planning', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='package_name',
            field=models.CharField(default='Standard Social Retainer', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='posters_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='posters_planned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='reels_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='stories_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='videos_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialmediaclient',
            name='videos_planned',
            field=models.IntegerField(default=0),
        ),
    ]
