# Generated by Django 6.1 on 2026-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_socialmediaclient_assigned_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaclient',
            name='deliverable_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
