# Generated by Django 6.1 on 2026-08-19 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=50)),
                ('message_type', models.CharField(default='Project Update', max_length=50)),
                ('message_text', models.TextField()),
                ('status', models.CharField(default='Sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
