# Generated by Django 6.1 on 2026-09-10 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.CharField(choices=[('SDLC', 'SDLC'), ('Waterfall', 'Waterfall'), ('Agile', 'Agile')], default='SDLC', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='activity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='methodology',
            field=models.CharField(choices=[('SDLC', 'SDLC'), ('Waterfall', 'Waterfall'), ('Agile', 'Agile')], default='SDLC', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
