# Generated by Django 6.1 on 2026-09-07 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Salaries & Payroll', 'Salaries & Payroll'), ('Cloud & Hosting', 'Cloud & Hosting'), ('Software & Subscriptions', 'Software & Subscriptions'), ('Office Rent', 'Office Rent'), ('Utilities & Internet', 'Utilities & Internet'), ('Marketing & Ad Spend', 'Marketing & Ad Spend'), ('Hardware & Equipment', 'Hardware & Equipment'), ('Vendor & Freelancers', 'Vendor & Freelancers'), ('Travel & Refreshments', 'Travel & Refreshments'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=30)),
                ('receipt_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Client Invoice', 'Client Invoice'), ('Marketing Retainer', 'Marketing Retainer'), ('Software Development', 'Software Development'), ('Consultation & Advisory', 'Consultation & Advisory'), ('AMC & Maintenance', 'AMC & Maintenance'), ('Other Revenue', 'Other Revenue')], default='Client Invoice', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Recurring', 'Recurring')], default='Received', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='clients.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='finance.invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='projects.project')),
            ],
        ),
    ]
