# Generated by Django 6.1 on 2026-09-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(blank=True, default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signature_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
