# Generated by Django 6.1 on 2026-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_quotation_client_details_quotation_company_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signature_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
