# Generated by Django 6.1 on 2026-09-07 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Keyboards & Mice', 'Keyboards & Mice'), ('Cables & Adapters', 'Cables & Adapters'), ('Storage & Memory', 'Storage & Memory'), ('Office Supplies & Stationery', 'Office Supplies & Stationery'), ('Branded Swag & Merch', 'Branded Swag & Merch'), ('Consumables & Miscellaneous', 'Consumables & Miscellaneous')], default='Cables & Adapters', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock_threshold', models.IntegerField(default=5)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(default='Main Supply Cabinet', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Laptops & Workstations', 'Laptops & Workstations'), ('Monitors & Displays', 'Monitors & Displays'), ('Studio & Media Cameras', 'Studio & Media Cameras'), ('Audio & Lighting Gear', 'Audio & Lighting Gear'), ('Networking & Servers', 'Networking & Servers'), ('Office Appliances & Furniture', 'Office Appliances & Furniture'), ('Other Equipment', 'Other Equipment')], default='Laptops & Workstations', max_length=50)),
                ('brand_model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('Retired / Damaged', 'Retired / Damaged')], default='Available', max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='HQ Tech Lab', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
