# Generated by Django 6.1 on 2026-08-19 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
