# Generated by Django 6.1 on 2026-08-19 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='System Admin', max_length=255)),
                ('user_role', models.CharField(default='Founder', max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('record_title', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
